name: github pages

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pandoc and doxygen 
        run: |
          sudo apt install pandoc doxygen

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: "pip"

      - name: Install dependencies
        run: python3 -m pip install -r ./requirements.txt

      - name: Build docs
        run: ./deploy_docs_action.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          keep_files: true
